# 구성 서버에 애플리케이션을 알려줌
spring:
  application:
    name: greetings
    
  cloud:
    config:
      uri: http://localhost:8888
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
