spring:
  datasource:
    schema:
      - order-schema.sql
      - ingredient-schema.sql
      - taco-schema.sql
      - user-schema.sql
    data:
      - ingredients.sql

# spring.datasource.jndi-name 속성을 설정하면 기존에 설정된 다른 데이터 소스 구성 속성은 무시됨
# ex) 위에 설정한 속성들은 jndi-name 속성에 따라 무시
    jndi-name: java:/comp/env/jdbc/tacoCloudDS