spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: info


management:
  endpoints:
    web:
      exposure:
        # 일부 엔드포인트를 제외한 나머지 엔드포인트 노출
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      # 모든 건강 지표를 자세하게 보겠음
      # 기본값은 never임
      show-details: always
  info:
    git:
      mode: full

