server:
  port: 9090

#spring:
#  security:
#    user:
#      name: admin
#      password: 53cr3t

# 아래 설정의 default는 true이고, Admin 서버가 유레카 클라이언트가 됨
# false로 설정하면 Admin 서버를 유레카 서비스로 등록
eureka:
  client:
    register-with-eureka: false
    # 유레카 서버가 기본 호스트와 포트에서 리스닝하지 않을때
    # 유레카 서버 명시
    #service-url:
    #  defaultZone: http://eureka1.tacocloud.com:8761/eureka/
